### ISSUE TITLE
Potential SQL injection

### ISSUE THREAD

**Issue by 409H** [uaktags/ez1.2.x-Modules#1]
https://github.com/uaktags/ez1.2.x-Modules/blob/Profile/modules/Profile/index.php#L35

You seem to be passing the raw `$_GET['player']` value into the query. Could lead to something not nice :-1:

**Comment by uaktags** [comment]
Great thanks, I'll be pushing a fix in the next few hours when i can get to my workstation.

**Comment by uaktags** [comment]
After looking it over, I don't believe that this risk is actually there.
The value is not passed without validation from the isClean function. 

Just as a proof of concept,

http://dev-1.2.x.ezrpgproject.net/index.php?mod=Profile&player=uaktags'; INSERT INTO dev12x_armies_trained (`player_id`, `army_id`) VALUES(1,50000);

This correctly fails due to the isClean check. Just to prove that, I went ahead and commented out the check and it correctly exploited the database. So the injection risk is prevented by the checks and the raw value is NOT passed to the data without first being checked.

Perhaps providing a PoC of an injection would be best? Or a suggestion on how to best improve this?
